services:

  simulator:
    build:
      context: .
      dockerfile: docker/simulator.Dockerfile
    container_name: simulator
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  corelogic:
    build:
      context: .
      dockerfile: docker/corelogic.Dockerfile
    container_name: corelogic
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  webui:
    build:
      context: .
      dockerfile: docker/webui.Dockerfile
    container_name: webui
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ensosphere
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
